### PR TITLE
fix travis

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Fixes rustfmt, which was broken on travis. Thanks!

### CODE REVIEW

**Comment by epage** [comment]
Id recommend checking out https://crate-ci.github.io/pr/rustfmt.html

It recommends pinning to stable, with examples, and has lots of other best practices with justifications, that I've taken from various blog posts and projects.

I have not heard of `cargo fmt --check` before, going to have to look into that.

**Comment by yoshuawuyts** [comment]
@killercup I'm not sure what the right approach is for that. Do you have an example?

I kind of would like to merge this patch as-is though, as currently CI is red across the board, and even a non-perfect solution is better than the current broken state we're in.

**Comment by killercup** [comment]
@yoshuawuyts Sure, merge this if it fixes stuff! A good approach is on the docs Ed linked to:

```yml
matrix:
  include:
  - env: RUSTFMT
    rust: 1.24.0  # `stable`: Locking down for consistent behavior
    install:
    - rustup component add rustfmt-preview
    script:
    - cargo fmt -- --write-mode=diff
```

**Comment by yoshuawuyts** [comment]
@epage oh yeah, the other flag has been deprecated recently. `-- --check` is now the way to run what previously used to be `-- --write-mode=diff`

**Comment by Dylan-DPC** [comment]
This will mean that in future contributors will have to change their version to 1.27.0 and run fmt before committing unless someone updates travis on every new release. Is that the plan?

**Comment by yoshuawuyts** [comment]
@Dylan-DPC we can always bump the versions. It feels like every option has inherent tradeoffs though, so probably going with what most people in the group feel comfortable with is reasonable. If it ever fails, we have enough people hanging out that it can be patched.

**Pull request merged**
